### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by fumi-y** [fumi-y/furima-35224#12]
### フリマアプリURL
https://furima-35224.herokuapp.com/
### Basic認証ID,Pass
- ID: admin
- Pass: 2222
### 出品者用のメールアドレスとパスワード
- email: test@test
- Pass: test11
### 購入者用のメールアドレスとパスワード
- email: test@com
- Pass: test22

**Comment by snkw-works** [comment]
@fumi-y さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/116017917-ce769c00-a67b-11eb-87a5-bdfaa4d8f97c.png)
